spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

    # 域名检测，启用时将进行解析以验证域名有效性
    # 注意: 开启此功能可能导致处理时间大幅延长
    domain-detect:
      enable: false
      timeout: 10

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
      - name: 5460
       path: https://raw.githubusercontent.com/qq5460168/dangchu/main/black.txt

      - name: 大萌主
      path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

       - name: DD
        path: https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt

      - name: AdRules DNS Filter
        path: https://raw.githubusercontent.com/Cats-Team/dns-filter/main/abp.txt

     - name: GitHub加速
        path: https://raw.hellogithub.com/hosts

     - name: 测试hosts
        path: https://raw.githubusercontent.com/qq5460168/dangchu/main/adhosts.txt

     - name: 白名单
        path: https://raw.githubusercontent.com/qq5460168/dangchu/main/white.txt

     - name: loveqqzj
      path: https://raw.githubusercontent.com/loveqqzj/AdGuard/master/Mobile.txt

    - name:
       path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
      
  - name: mphin
      path: https://raw.githubusercontent.com/mphin/AdGuardHomeRules/main/Blacklist.txt
      
     - name: 周木木
      path: https://gitee.com/zjqz/ad-guard-home-dns/raw/master/black-list
      
     - name: liwenjie119
       path: https://raw.githubusercontent.com/liwenjie119/adg-rules/master/black.txt
      
     - name: FCM Hosts
       path: https://github.com/entr0pia/fcm-hosts/raw/fcm/fcm-hosts

    - name:
      path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt

   - name: 秋风规则
     path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf

   - name: 喵二
     path: https://raw.githubusercontent.com/qq5460168/dangchu/refs/heads/main/777.txt
      

    #本地规则文件
    local:
      - name: 'local rule'
        path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)
    file_header: |
      ADFS AdBlock ${type}
      Last Modified: ${date}
      Homepage: https://github.com/fordes123/ad-filters-subscriber/

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进，且每个类型只能输出一个文件）
    files:
      - name: easylist.txt     #必要参数: 文件名
        type: easylist         #必要参数: 文件类型: easylist、dnsmasq、clash、smartdns、hosts
        desc: 'ADFS EasyList'  #可选参数: 文件描述，可在file_header中通过 ${} 中使用
        filter:
          - basic              #基本规则，不包含任何控制、匹配符号, 可以转换为 hosts
          - wildcard           #通配规则，仅使用通配符
          - unknown            #其他规则，如使用了正则、高级修饰符号等，这表示目前无法支持

      - name: dns.txt
        type: easylist
        filter:
          - basic
          - wildcard

      - name: dnsmasq.txt
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.txt
        type: smartdns

      - name: hosts.txt
        type: hosts
